/**
 * Cloudflare Workers AI Client
 *
 * Cloudflare 내장 AI를 사용한 LLM 클라이언트.
 * - Model: @cf/meta/llama-3.3-70b-instruct-fp8-fast
 * - 지역 제한 없음, 외부 API 키 불필요
 * - Strict JSON 출력 + evolution_note 필드 지원
 * - 시스템 갭 자가 진단 (gap_detected)
 */

export interface AgentContext {
  taskId: string;
  taskName: string;
  persona: string;
  input: unknown;
  localResult: unknown;
  shortTermMemory?: string; // 세션 컨텍스트 (최근 대화 요약)
  userPreferences?: UserPreferences; // 사용자 선호도
}

export interface UserPreferences {
  language?: string;
  detail_level?: "brief" | "standard" | "detailed";
  industry_focus?: string;
  past_topics?: string[];
}

export interface DetectedGap {
  type: "MISSING_FEAT" | "LOGIC_ERROR" | "USER_FRUSTRATION" | "DATA_GAP" | "PERF_ISSUE";
  severity: "low" | "medium" | "high" | "critical";
  description: string;
  suggested_fix?: string;
}

export interface AIInsights {
  analysis: string;
  recommendations: string[];
  risk_factors: string[];
  confidence_score: number;
  evolution_note?: string; // AI 자기 학습 메모
  gap_detected?: DetectedGap; // 시스템 한계 자가 진단
}

export interface EnhancedResult {
  enhanced_result: unknown;
  ai_insights: AIInsights;
}

/**
 * Cloudflare Workers AI 클라이언트
 */
export class CloudflareAIClient {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private ai: any;
  private model = "@cf/meta/llama-3.3-70b-instruct-fp8-fast";

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  constructor(ai: any) {
    this.ai = ai;
  }

  /**
   * 에이전트 결과 보강
   *
   * 로컬 로직 실행 결과를 Llama 3.3이 검토하고 보강된 인사이트 제공
   * - Strict JSON 출력 모드
   * - evolution_note: AI 자기 학습 메모
   * - gap_detected: 시스템 한계 자가 진단
   * - Short-term Memory: 세션 컨텍스트 주입
   * - User Preferences: 사용자 맞춤화
   */
  async enhanceAgentResult(context: AgentContext): Promise<EnhancedResult> {
    const memorySection = context.shortTermMemory || "";
    const prefSection = context.userPreferences
      ? `\n## User Preferences\n${JSON.stringify(context.userPreferences, null, 2)}\n`
      : "";

    const systemPrompt = `${context.persona}

You are an expert event planning AI following CMP-IS (Certified Meeting Professional - International Standards) standards.
${memorySection}${prefSection}

## Your Role
1. Review the results generated by local logic algorithms.
2. Evaluate accuracy, completeness, and alignment with industry best practices.
3. Provide actionable insights and recommendations.
4. Identify potential risks and mitigation strategies.
5. Learn from this interaction and note improvements for future responses.
6. **CRITICAL**: Detect any system limitations or gaps where you cannot fully answer the user's needs.

## STRICT JSON OUTPUT FORMAT
You MUST respond with ONLY a valid JSON object. NO markdown, NO code blocks, NO explanatory text.

Required structure:
{
  "enhanced_result": <original result with any corrections or additions>,
  "ai_insights": {
    "analysis": "Concise analysis of the result (max 200 chars)",
    "recommendations": ["actionable recommendation 1", "actionable recommendation 2"],
    "risk_factors": ["identified risk 1", "identified risk 2"],
    "confidence_score": 0.85,
    "evolution_note": "What I learned from this interaction that could improve future responses",
    "gap_detected": null or {
      "type": "MISSING_FEAT|LOGIC_ERROR|USER_FRUSTRATION|DATA_GAP|PERF_ISSUE",
      "severity": "low|medium|high|critical",
      "description": "What capability is missing or what went wrong",
      "suggested_fix": "How this gap could be addressed in future versions"
    }
  }
}

## GAP DETECTION RULES
Detect a gap when:
- User asks about a feature that doesn't exist (MISSING_FEAT)
- The local logic result seems incorrect or incomplete (LOGIC_ERROR)
- User's question implies frustration or repeated attempts (USER_FRUSTRATION)
- Insufficient data to provide accurate response (DATA_GAP)
- Response took too long or was truncated (PERF_ISSUE)

If no gap detected, set gap_detected to null.

CRITICAL RULES:
- Output ONLY the JSON object, nothing else
- confidence_score must be a number between 0.0 and 1.0
- Always evaluate if there's a system gap to report`;

    const userPrompt = `## Task: ${context.taskId} - ${context.taskName}

## Input Data:
${JSON.stringify(context.input, null, 2)}

## Local Logic Result:
${JSON.stringify(context.localResult, null, 2)}

Analyze this result. If you detect ANY limitation in the current system's ability to serve this request, report it in gap_detected. Output ONLY valid JSON.`;

    try {
      const response = await this.ai.run(this.model, {
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        max_tokens: 2048,
        temperature: 0.7,
      });

      // 응답 파싱
      const responseText =
        typeof response === "string"
          ? response
          : (response as { response?: string }).response || "";

      return this.parseResponse(responseText, context.localResult);
    } catch (error) {
      console.error("Cloudflare AI error:", error);
      // 실패 시 기본 응답 반환
      return {
        enhanced_result: context.localResult,
        ai_insights: {
          analysis: "AI enhancement unavailable",
          recommendations: [],
          risk_factors: [],
          confidence_score: 0.5,
        },
      };
    }
  }

  /**
   * 응답 파싱
   */
  private parseResponse(
    responseText: string,
    fallbackResult: unknown
  ): EnhancedResult {
    try {
      // JSON 블록 추출 시도
      const jsonMatch = responseText.match(/\{[\s\S]*\}/);
      const jsonStr = jsonMatch ? jsonMatch[0] : responseText;

      const parsed = JSON.parse(jsonStr.trim());

      // 필수 필드 검증
      if (parsed.ai_insights && parsed.enhanced_result !== undefined) {
        return parsed as EnhancedResult;
      }

      // ai_insights만 있는 경우
      if (parsed.ai_insights) {
        return {
          enhanced_result: fallbackResult,
          ai_insights: parsed.ai_insights,
        };
      }

      throw new Error("Invalid response structure");
    } catch {
      // 파싱 실패 시 텍스트 분석으로 대체
      return {
        enhanced_result: fallbackResult,
        ai_insights: {
          analysis: responseText.slice(0, 500),
          recommendations: [],
          risk_factors: [],
          confidence_score: 0.5,
        },
      };
    }
  }

  /**
   * 간단한 텍스트 생성
   */
  async chat(systemPrompt: string, userMessage: string): Promise<string> {
    const response = await this.ai.run(this.model, {
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userMessage },
      ],
      max_tokens: 1024,
      temperature: 0.7,
    });

    return typeof response === "string"
      ? response
      : (response as { response?: string }).response || "";
  }
}

/**
 * Cloudflare AI 클라이언트 인스턴스 생성
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function createAIClient(ai: any): CloudflareAIClient {
  if (!ai) {
    throw new Error("Cloudflare AI binding is required");
  }
  return new CloudflareAIClient(ai);
}

export default CloudflareAIClient;
